apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promtail-cluster-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promtail-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: promtail-cluster-role
subjects:
- kind: ServiceAccount
  name: promtail-sa
  namespace: log-namespace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail-sa
  namespace: log-namespace
---
apiVersion: v1
kind: Pod
metadata:
  name: log-generator-1
  namespace: log-namespace
  labels:
    foo: bar
spec:
  containers:
  - name: log-generator
    image: busybox
    args:
    - /bin/sh
    - -c
    - |
      while true; do
        echo "$(date) - log from log-generator-1";
        sleep 1;
      done

---
apiVersion: v1
kind: Pod
metadata:
  name: log-generator-2
  namespace: log-namespace
  labels:
    foo: bar
spec:
  containers:
  - name: log-generator
    image: busybox
    args:
    - /bin/sh
    - -c
    - |
      while true; do
        echo "$(date) - log from log-generator-2";
        sleep 1;
      done

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: log-namespace
data:
  promtail-config.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki-k8s-0.loki-k8s-endpoints.log-namespace.svc.cluster.local:3100/loki/api/v1/push

    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
            selectors:
              - role: pod
                label: "foo=bar"
        relabel_configs:
          # Keep metadata labels from Kubernetes
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: pod
          - source_labels: [__meta_kubernetes_pod_container_name]
            action: replace
            target_label: container
          - source_labels: [__meta_kubernetes_pod_uid]
            action: replace
            target_label: pod_uid
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_name, __meta_kubernetes_pod_uid, __meta_kubernetes_pod_container_name]
            action: replace
            target_label: __path__
            regex: (.+);(.+);(.+);(.+)
            replacement: /var/snap/microk8s/common/var/log/pods/${1}_${2}_${3}/${4}/*.log
---
apiVersion: v1
kind: Pod
metadata:
  name: promtail
  namespace: log-namespace
spec:
  serviceAccountName: promtail-sa
  containers:
  - name: promtail
    image: grafana/promtail:3.1.2
    args:
      - -config.file=/etc/promtail/promtail-config.yaml
      - -log.level=debug
    volumeMounts:
    - name: promtail-config
      mountPath: /etc/promtail
    - name: var-log
      mountPath: /var/snap/microk8s/common/var/log/pods
  volumes:
  - name: promtail-config
    configMap:
      name: promtail-config
  - name: var-log
    hostPath:
      path: /var/snap/microk8s/common/var/log/pods  # Host path for log files